// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title CertificateRegistry
 * @dev CredChain - Blockchain Certificate Registry for KTU
 *      Certificate PDFs are stored on IPFS (Pinata).
 *      This contract stores the IPFS hash + metadata on-chain.
 */
contract CertificateRegistry {

    struct Certificate {
        string  certId;       // Unique ID (UUID generated by backend)
        string  ipfsHash;     // Pinata/IPFS CID of the certificate PDF
        address issuedBy;     // Ethereum address of issuer (KTU wallet)
        uint256 issuedAt;     // Unix timestamp
        bool    isValid;      // false = revoked
        string  studentId;    // MongoDB student ID or email
        string  courseName;   // e.g. "MCA", "B.Tech CSE"
        uint16  year;         // Year of completion
    }

    mapping(string => Certificate) private certificates;
    string[] public allCertIds;
    address public owner;

    // ── Events ──────────────────────────────────────────────
    event CertificateIssued(
        string  indexed certId,
        string          ipfsHash,
        address indexed issuedBy,
        uint256         timestamp,
        string          studentId
    );
    event CertificateRevoked(
        string  indexed certId,
        address indexed revokedBy,
        uint256         timestamp
    );

    constructor() {
        owner = msg.sender;
    }

    // ── Write Functions ──────────────────────────────────────

    function issueCertificate(
        string memory certId,
        string memory ipfsHash,
        string memory studentId,
        string memory courseName,
        uint16        year
    ) public {
        require(bytes(certId).length > 0,   "certId is required");
        require(bytes(ipfsHash).length > 0, "ipfsHash is required");
        require(
            bytes(certificates[certId].certId).length == 0,
            "Certificate already exists"
        );

        certificates[certId] = Certificate({
            certId:     certId,
            ipfsHash:   ipfsHash,
            issuedBy:   msg.sender,
            issuedAt:   block.timestamp,
            isValid:    true,
            studentId:  studentId,
            courseName: courseName,
            year:       year
        });

        allCertIds.push(certId);
        emit CertificateIssued(certId, ipfsHash, msg.sender, block.timestamp, studentId);
    }

    function revokeCertificate(string memory certId) public {
        require(bytes(certificates[certId].certId).length != 0, "Certificate not found");
        require(certificates[certId].isValid,              "Already revoked");
        require(certificates[certId].issuedBy == msg.sender, "Only original issuer can revoke");

        certificates[certId].isValid = false;
        emit CertificateRevoked(certId, msg.sender, block.timestamp);
    }

    // ── Read Functions ───────────────────────────────────────

    function verifyCertificate(string memory certId)
        public view
        returns (
            bool    isValid,
            string  memory ipfsHash,
            address issuedBy,
            uint256 issuedAt,
            string  memory studentId,
            string  memory courseName,
            uint16  year
        )
    {
        Certificate memory cert = certificates[certId];
        require(bytes(cert.certId).length != 0, "Certificate not found");
        return (cert.isValid, cert.ipfsHash, cert.issuedBy, cert.issuedAt,
                cert.studentId, cert.courseName, cert.year);
    }

    function certificateExists(string memory certId) public view returns (bool) {
        return bytes(certificates[certId].certId).length != 0;
    }

    function totalCertificates() public view returns (uint256) {
        return allCertIds.length;
    }
}
